version: '3.8'
services:
  db:
    image: mysql:8.0.32
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'wordoccurrences'
      MYSQL_USER: 'wordoccurrences'
      MYSQL_PASSWORD: 'changeme'
    ports:
      - '3306:3306'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql